/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as keyNftSol from "./KeyNFT.sol";
export type { keyNftSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as oracle from "./oracle";
export type { oracle };
export type { PlxyerStore } from "./PlxyerStore";
